language: d

sudo: false

d:
  - dmd #-2.068.1
  - dmd-2.067.0
  - dmd-2.066.1
  - dmd-2.065.0
  - ldc #-0.15.1
  - ldc-0.14.0
  - ldc-0.16.0-beta1
  - gdc #-4.9.3
  - gdc-4.9.0

script:
  - dub test --compiler=$DC || exit 1
